apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: dmitriipolushin/lab2_python_app:latest
        ports:
        - containerPort: 8000